# Generated by Django 4.0 on 2022-01-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paint',
            name='category',
        ),
        migrations.AddField(
            model_name='paint',
            name='category',
            field=models.ManyToManyField(related_name='category', to='eshop.Category'),
        ),
    ]
