# Generated by Django 4.0 on 2022-01-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_alter_paint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='image',
            field=models.ImageField(upload_to='./products'),
        ),
    ]
