# Generated by Django 4.0 on 2022-01-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paint',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
