# Generated by Django 4.0 on 2022-01-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_alter_paint_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='image',
            field=models.ImageField(upload_to='./static/products'),
        ),
    ]
