# Generated by Django 4.0 on 2022-01-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_order_total_alter_paint_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='eshop.Paint'),
        ),
    ]
