# Generated by Django 4.0 on 2022-01-15 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_alter_paint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='number_of_products',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='order_item',
        ),
        migrations.AddField(
            model_name='orderline',
            name='order_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='eshop.paint'),
        ),
    ]
