# Generated by Django 4.0 on 2022-01-29 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
