# Generated by Django 4.0 on 2022-01-29 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_remove_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='works',
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paint',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='eshop.author'),
            preserve_default=False,
        ),
    ]
